### ISSUE TITLE
Enable write access

### ISSUE THREAD

**Issue by libaf** [kasemir/dbwr#4]
Hi,
I've accessed a .bob-display using the dbwr which reads changes of different records. However, I don't manage to write to any records. In PV Web Socket I suscribed to a PV and then tried to write to it, which return the error PV_WRITE_SUPPORT is disabled, even though I already tried setting the environmental variable PV_WRITE_SUPPORT=true. Would you have any idea of how to progress here?
Cheers,
Markus Kristensson,
Libaf

**Comment by kasemir** [comment]
Note that the write support is not in `dbwr` but in the PV service, `pvws`, but you'll likely run both within the same Tomcat instance, so they see the same environment variables.
I've just updated `pwws` to log the values of its key environment variables on startup, https://github.com/kasemir/pvws/commit/cf5c54c62fad0ec5c9730072b5b8a7db042b9858.
So check if you're really setting `PV_WRITE_SUPPORT=true`:
```
Oct 15, 2020 8:42:36 AM pvws.PVWebSocketContext contextInitialized
INFO: Environment:
EPICS_CA_ADDR_LIST =...
..
PV_WRITE_SUPPORT = true
```

**Comment by libaf** [comment]
Thanks for your update. It turned out that the setenv.sh was not read in. Solution for now was to put the settings into the tomcat.conf file instead.

**Comment by kasemir** [comment]
Yes, details depend on the tomcat version and how it's installed.
Note that opening write access is inherently dangerous.
The CA server (IOC) has no idea who's really in front of the web browser. To the IOC, all access appears to originate from the 'tomcat' user on the host that runs tomcat. You probably want to put a httpd proxy with some login mechanism on top of tomcat to control who can access it.

**Comment by libaf** [comment]
Thanks for your input!
